#!/bin/sh
# Emit web/dashboard-src/utils/motor-reference-traces.js from the Rev 3.3 CI
# fixtures, keeping only the columns the Motor Lab threshold explorer reads.
# Run `make dashboard-reference-traces` after replacing a fixture; the dashboard
# test fails when the generated module and the fixtures disagree.
set -eu
root=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)

emit() {
  awk -F, -v name="$1" '
    NR == 1 { for (i = 1; i <= NF; i++) col[$i] = i; next }
    {
      if (!printed) { printf "export const %s = [\n", name; printed = 1 }
      printf "  [%d,%d,%.1f,%d],\n", $col["t_ms"], $col["motion_count"], $col["current_ma"], $col["stroke_phase"]
    }
    END { print "];" }
  ' "$2"
}

{
  echo "// GENERATED by scripts/gen-reference-traces.sh from test/fixtures - do not edit."
  echo "// Rows: [t_ms, motion_count, current_ma, stroke_phase]. Captured on Rev 3.3;"
  echo "// the close run destroyed the actuator and the open run is the same broken unit."
  echo
  emit REFERENCE_CLOSE "$root/test/fixtures/motor-lab-z1-close.csv"
  echo
  emit REFERENCE_OPEN "$root/test/fixtures/motor-lab-z1-open.csv"
  echo
  echo "export function referenceSamples(rows) {"
  echo "  return rows.map(([t_ms, motion_count, current_ma, stroke_phase]) => ({ t_ms, motion_count, current_ma, stroke_phase }));"
  echo "}"
}
