// utils/keys.js

export const key = {
  temp: (zone) => 'sensor-zone_' + zone + '_temperature',
  setpoint: (zone) => 'number-zone_' + zone + '_setpoint',
  climate: (zone) => 'climate-zone_' + zone,
  valve: (zone) => 'sensor-zone_' + zone + '_valve_pct',
  state: (zone) => 'text_sensor-zone_' + zone + '_state',
  enabled: (zone) => 'switch-zone_' + zone + '_enabled',
  probe: (zone) => 'select-zone_' + zone + '_probe',
  tempSource: (zone) => 'select-zone_' + zone + '_temp_source',
  syncTo: (zone) => 'select-zone_' + zone + '_sync_to',
  pipeType: (zone) => 'select-zone_' + zone + '_pipe_type',
  area: (zone) => 'number-zone_' + zone + '_area_m2',
  spacing: (zone) => 'number-zone_' + zone + '_pipe_spacing_mm',
  ble: (zone) => 'text-zone_' + zone + '_ble_mac',
  name: (zone) => 'text-zone_' + zone + '_name',
  exteriorWalls: (zone) => 'text-zone_' + zone + '_exterior_walls',
  motorTarget: (zone) => 'number-motor_' + zone + '_target_position',
  motorOpenRipples: (zone) => 'sensor-motor_' + zone + '_learned_open_ripples',
  motorCloseRipples: (zone) => 'sensor-motor_' + zone + '_learned_close_ripples',
  motorOpenFactor: (zone) => 'sensor-motor_' + zone + '_learned_open_factor',
  motorCloseFactor: (zone) => 'sensor-motor_' + zone + '_learned_close_factor',
  preheatAdvance: (zone) => 'sensor-zone_' + zone + '_preheat_advance_c',
  motorLastFault: (zone) => 'text_sensor-motor_' + zone + '_last_fault',
  probeTemp: (probe) => 'sensor-probe_' + probe + '_temperature'
};

export const gkey = {
  deviceVariant: 'text-device_variant',
  flow: 'sensor-manifold_flow_temperature',
  ret: 'sensor-manifold_return_temperature',
  uptime: 'sensor-uptime',
  wifi: 'sensor-wifi_signal',
  drivers: 'switch-motor_drivers_enabled',
  fault: 'binary_sensor-motor_fault',
  ip: 'text_sensor-ip_address',
  ssid: 'text_sensor-connected_ssid',
  mac: 'text_sensor-mac_address',
  firmware: 'text_sensor-firmware_version',
  manifoldFlowProbe: 'select-manifold_flow_probe',
  manifoldReturnProbe: 'select-manifold_return_probe',
  manifoldType: 'select-manifold_type',
  motorProfileDefault: 'select-motor_profile_default',
  closeThresholdMultiplier: 'number-close_threshold_multiplier',
  closeSlopeThreshold: 'number-close_slope_threshold',
  closeSlopeCurrentFactor: 'number-close_slope_current_factor',
  openThresholdMultiplier: 'number-open_threshold_multiplier',
  openSlopeThreshold: 'number-open_slope_threshold',
  openSlopeCurrentFactor: 'number-open_slope_current_factor',
  openRippleLimitFactor: 'number-open_ripple_limit_factor',
  genericRuntimeLimitSeconds: 'number-generic_runtime_limit_seconds',
  hmipRuntimeLimitSeconds: 'number-hmip_runtime_limit_seconds',
  relearnAfterMovements: 'number-relearn_after_movements',
  relearnAfterHours: 'number-relearn_after_hours',
  learnedFactorMinSamples: 'number-learned_factor_min_samples',
  learnedFactorMaxDeviationPct: 'number-learned_factor_max_deviation_pct',
  simplePreheatEnabled: 'switch-simple_preheat_enabled',
  preheatAbsorbEnabled: 'switch-preheat_absorb_enabled',
  preheatAbsorbBandC: 'number-preheat_absorb_band_c',
  preheatDetectDeltaC: 'number-preheat_detect_delta_c',
  preheatAbsorbing: 'text-preheat_absorbing',
  asgardEnabled: 'switch-asgard_enabled',
  asgardCoordinator: 'switch-asgard_coordinator',
  asgardHost: 'text-asgard_host',
  asgardPort: 'number-asgard_port',
  asgardEntityName: 'text-asgard_entity_name',
  asgardPeerHost: 'text-asgard_peer_host',
  asgardPushIntervalS: 'number-asgard_push_interval_s',
  asgardRole: 'text-asgard_role',
  asgardPeerStatus: 'text-asgard_peer_status',
  asgardLastError: 'text-asgard_last_error',
  asgardLastPushC: 'sensor-asgard_last_push_c',
  asgardSetpointC: 'sensor-asgard_setpoint_c',
  asgardLastPushAgeS: 'sensor-asgard_last_push_age_s',
  asgardLocalZones: 'sensor-asgard_local_zones',
  asgardPeerZones: 'sensor-asgard_peer_zones',
  minimumFlowAlways: 'switch-minimum_flow_always',
  minZoneFlowPct: 'number-min_zone_flow_pct',
  cpuLoadCore0: 'sensor-cpu_load_core0',
  cpuLoadCore1: 'sensor-cpu_load_core1',
  freeInternalKb: 'sensor-free_internal_kb',
  freePsramKb: 'sensor-free_psram_kb',
};
