// utils/keys.js

export const key = {
  temp: (zone) => 'sensor-zone_' + zone + '_temperature',
  setpoint: (zone) => 'number-zone_' + zone + '_setpoint',
  baseSetpoint: (zone) => 'number-zone_' + zone + '_base_setpoint',
  effectiveSetpoint: (zone) => 'number-zone_' + zone + '_effective_setpoint',
  coordinatorOffset: (zone) => 'number-zone_' + zone + '_coordinator_offset',
  coordinatorRemaining: (zone) => 'sensor-zone_' + zone + '_coordinator_remaining_s',
  climate: (zone) => 'climate-zone_' + zone,
  valve: (zone) => 'sensor-zone_' + zone + '_valve_pct',
  state: (zone) => 'text_sensor-zone_' + zone + '_state',
  enabled: (zone) => 'switch-zone_' + zone + '_enabled',
  probe: (zone) => 'select-zone_' + zone + '_probe',
  tempSource: (zone) => 'select-zone_' + zone + '_temp_source',
  syncTo: (zone) => 'select-zone_' + zone + '_sync_to',
  ble: (zone) => 'text-zone_' + zone + '_ble_mac',
  name: (zone) => 'text-zone_' + zone + '_name',
  motorTarget: (zone) => 'number-motor_' + zone + '_target_position',
  motorOpenRipples: (zone) => 'sensor-motor_' + zone + '_learned_open_ripples',
  motorCloseRipples: (zone) => 'sensor-motor_' + zone + '_learned_close_ripples',
  motorOpenFactor: (zone) => 'sensor-motor_' + zone + '_learned_open_factor',
  motorCloseFactor: (zone) => 'sensor-motor_' + zone + '_learned_close_factor',
  preheatAdvance: (zone) => 'sensor-zone_' + zone + '_preheat_advance_c',
  motorLastFault: (zone) => 'text_sensor-motor_' + zone + '_last_fault',
  probeTemp: (probe) => 'sensor-probe_' + probe + '_temperature'
};

export const gkey = {
  deviceVariant: 'text-device_variant',
  flow: 'sensor-manifold_flow_temperature',
  ret: 'sensor-manifold_return_temperature',
  uptime: 'sensor-uptime',
  wifi: 'sensor-wifi_signal',
  drivers: 'switch-motor_drivers_enabled',
  fault: 'binary_sensor-motor_fault',
  ip: 'text_sensor-ip_address',
  ssid: 'text_sensor-connected_ssid',
  mac: 'text_sensor-mac_address',
  firmware: 'text_sensor-firmware_version',
  manifoldFlowProbe: 'select-manifold_flow_probe',
  manifoldReturnProbe: 'select-manifold_return_probe',
  manifoldType: 'select-manifold_type',
  motorProfileDefault: 'select-motor_profile_default',
  closeThresholdMultiplier: 'number-close_threshold_multiplier',
  closeSlopeThreshold: 'number-close_slope_threshold',
  closeSlopeCurrentFactor: 'number-close_slope_current_factor',
  openThresholdMultiplier: 'number-open_threshold_multiplier',
  openSlopeThreshold: 'number-open_slope_threshold',
  openSlopeCurrentFactor: 'number-open_slope_current_factor',
  openRippleLimitFactor: 'number-open_ripple_limit_factor',
  genericRuntimeLimitSeconds: 'number-generic_runtime_limit_seconds',
  hmipRuntimeLimitSeconds: 'number-hmip_runtime_limit_seconds',
  relearnAfterMovements: 'number-relearn_after_movements',
  relearnAfterHours: 'number-relearn_after_hours',
  learnedFactorMinSamples: 'number-learned_factor_min_samples',
  learnedFactorMaxDeviationPct: 'number-learned_factor_max_deviation_pct',
  simplePreheatEnabled: 'switch-simple_preheat_enabled',
  preheatAbsorbEnabled: 'switch-preheat_absorb_enabled',
  preheatAbsorbBandC: 'number-preheat_absorb_band_c',
  preheatDetectDeltaC: 'number-preheat_detect_delta_c',
  preheatAbsorbing: 'text-preheat_absorbing',
  authorityState: 'text-authority_state',
  authorityReason: 'text-authority_reason',
  authorityInstallationId: 'text-authority_installation_id',
  authorityCoordinatorId: 'text-authority_coordinator_id',
  authorityProposalInstallationId: 'text-authority_proposal_installation_id',
  authorityProposalCoordinatorId: 'text-authority_proposal_coordinator_id',
  authorityProposalName: 'text-authority_proposal_name',
  authorityProposalSite: 'text-authority_proposal_site',
  authorityProposalPending: 'binary_sensor-authority_proposal_pending',
  authorityConfigured: 'binary_sensor-authority_configured',
  authorityLeaseRemainingS: 'sensor-authority_lease_remaining_s',
  minimumFlowAlways: 'switch-minimum_flow_always',
  minZoneFlowPct: 'number-min_zone_flow_pct',
  cpuLoadCore0: 'sensor-cpu_load_core0',
  cpuLoadCore1: 'sensor-cpu_load_core1',
  freeInternalKb: 'sensor-free_internal_kb',
  freePsramKb: 'sensor-free_psram_kb',
};
